name: Spell Check

on:
  pull_request:
    paths:
      - 'content/**/*.adoc'
      - '.github/workflows/spell-check.yml'
      - '.github/workflows/.cspell.json'
  push:
    branches: [ main ]
    paths:
      - 'content/**/*.adoc'
      - '.github/workflows/spell-check.yml'
      - '.github/workflows/.cspell.json'

jobs:
  spell-check:
    runs-on: ubuntu-latest
    name: Spell Check Documentation
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install cspell
        run: npm install -g cspell
        
      - name: Run spell check
        run: |
          cspell \
            --config ./.github/workflows/.cspell.json \
            --no-progress \
            --show-context \
            --show-suggestions \
            "content/**/*.adoc"
        
      - name: Comment on PR (if spell check fails)
        if: failure() && github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `❌ **Spell check failed**
              
              Please review the spell check errors above and either:
              - Fix the spelling errors
              - Add technical terms to the project dictionary in \`.github/workflows/.cspell.json\`
              
              Re-run the spell check locally with:
              \`\`\`bash
              npx cspell --config ./.github/workflows/.cspell.json "content/**/*.adoc"
              \`\`\`
              `
            })
            
      - name: Output spell check failure message
        if: failure() && github.event_name == 'pull_request'
        run: |
          echo "❌ Spell check failed!"
          echo "Please review the spell check errors above and either:"
          echo "- Fix the spelling errors"
          echo "- Add technical terms to the project dictionary in .github/workflows/.cspell.json"
          echo ""
          echo "Re-run the spell check locally with:"
          echo "npx cspell --config ./.github/workflows/.cspell.json \"content/**/*.adoc\"" 